// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:main.Settings):Promise<main.Status>;

export function Delete(arg1:string):Promise<boolean>;

export function Disconnect():Promise<main.Status>;

export function Get(arg1:string):Promise<string>;

export function LoadSettings():Promise<main.Settings>;

export function Nodes():Promise<Array<main.Node>>;

export function Scan(arg1:string,arg2:number,arg3:number):Promise<main.ScanResult>;

export function Set(arg1:string,arg2:string,arg3:number):Promise<void>;

export function Status():Promise<main.Status>;
