// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Delete(arg1) {
  return window['go']['main']['App']['Delete'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function Get(arg1) {
  return window['go']['main']['App']['Get'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function Nodes() {
  return window['go']['main']['App']['Nodes']();
}

export function Scan(arg1, arg2, arg3) {
  return window['go']['main']['App']['Scan'](arg1, arg2, arg3);
}

export function Set(arg1, arg2, arg3) {
  return window['go']['main']['App']['Set'](arg1, arg2, arg3);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}
