// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetValue(arg1:string):Promise<string>;

export function SetValue(arg1:string,arg2:string):Promise<string>;

export function UpdateConnection(arg1:string,arg2:string):Promise<string>;
