// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetValue(arg1) {
  return window['go']['main']['App']['GetValue'](arg1);
}

export function SetValue(arg1, arg2) {
  return window['go']['main']['App']['SetValue'](arg1, arg2);
}

export function UpdateConnection(arg1, arg2) {
  return window['go']['main']['App']['UpdateConnection'](arg1, arg2);
}
